package enumstorage.database

enum class DatabaseCommand {
    AddColor,
    DeleteAllColors,
    DeleteColor,
    GetAllColors,
    UpdateColorById,

    AddDevice,
    DeleteAllDevices,
    DeleteDevice,
    GetAllDevices,
    UpdateDeviceById,

    AddGobo,
    DeleteAllGobos,
    DeleteGobo,
    GetAllGobos,
    UpdateGoboById,

    AddImage,
    DeleteAllImages,
    DeleteImage,
    GetAllImages,
    UpdateImageById,

    AddManufacturer,
    DeleteAllManufacturers,
    DeleteManufacturer,
    GetAllManufacturers,
    UpdateManufacturerById,

    AddType,
    DeleteAllTypes,
    DeleteType,
    GetAllTypes,
    UpdateTypeById,

    AddConfiguration,
    DeleteAllConfigurations,
    DeleteConfiguration,
    GetAllConfigurations,
    GetConfigurationByDdfHash,
    GetConfigurationBySsid,
    UpdateConfigurationBySsid,

    DeleteShow,
    EnableShow,
    GetAllShows,
    GetEnabledShow,
    IsShowAvailable,
    AddShow,
    RenameShow,

    AddSlave,
    CheckIfSlaveIsAvailable,
    DeleteAllSlaves,
    DeleteSlave,
    GetAllSlaves,
    GetGeoByMacAddress,
    GetNewSsid,
    GetNumberOfSlaves,
    GetSlaveByDevice,
    GetSlaveByEnabledRotation,
    GetSlaveByMacAddress,
    GetSlaveByManufacturer,
    GetSlaveBySsid,
    GetSlaveByType,
    SaveSlaveBackup,
    UpdateGeo,
    UpdateRotation,
    UpdateAllSlavesWhere,
    UpdateSlaveByMacAddress,
    UpdateSlaveBySsid,
    UpdateTimestamp,
    UpdateInformationBySsid
}